### PR TITLE
Fix fallbacks support in jss-plugin-vendor-prefixer

### LINKED ISSUE #1177: Multiple fallbacks for the same property name not working
**Expected behavior:**
When an array is used for the fallbacks value it should render multiple properties for the same property name

**Describe the bug:**
The array of fallbacks are being render like this:

```
.Component-withFallbacks-2-2-1 {
  0: [;
  1: o;
  2: b;
  3: j;
  ...
  29: c;
  30: t;
  31: ];
  display: flex;
}
```

The jss vendor prefix plugin seems to be changing it into the string
`"[object Object], [object Object]"`

**Codesandbox link:**
[https://codesandbox.io/s/jss-fallbacks-problem-gbvkf](https://codesandbox.io/s/jss-fallbacks-problem-gbvkf)

__Versions (please complete the following information):__
 - jss: 10.0.0-alpha.24
 - Browser: Chrome
 - OS Windows and macOS

### PR DESCRIPTION
**Pull request by kof**
fixes #1177

### CODE REVIEW

File: packages/jss-plugin-vendor-prefixer/src/index.js [hunk 1]
```diff
@@ -15,12 +15,13 @@ export default function jssVendorPrefixer(): Plugin {
...
   }
 
-  function onProcessStyle(style, rule) {
-    if (rule.type !== 'style') return style
-
+  function prefixStyle(style) {
     for (const prop in style) {
       const value = style[prop]
-
+      if (prop === 'fallbacks' && Array.isArray(value)) {
```
Comment (HenriBeck) [inline packages/jss-plugin-vendor-prefixer/src/index.js]: Should we also handle fallbacks which are just an object?

Comment (kof) [reply packages/jss-plugin-vendor-prefixer/src/index.js]: adding a test

Comment (kof) [reply packages/jss-plugin-vendor-prefixer/src/index.js]: added a test, it already works.
