### PR TITLE
Always use insertRule API with option link: true

### LINKED ISSUE #815: "Rule is not linked" error for function rules with non-canonical selector formatting
Minimal reproduction: https://codesandbox.io/s/016vzn15ol

If I define two dynamic rules like this:

```javascript
  nospace: {
    "@media (min-width:1px)": {
      color: ({ color }) => color
    }
  },
  space: {
    "@media (min-width: 1px)": {
      color: ({ color }) => color
    }
  },
```

The first one does not work, but the second one does. The difference is the missing space between `min-width:` and `1px`.

I’ve tracked this down to [RuleList.link()](https://github.com/cssinjs/jss/blob/3ccac24bc31837d2727f4b51838f2b629e46871d/packages/jss/src/RuleList.js#L157) where the key given by `DomRenderer.getKey()` is sanitised by the browser, whereas the key originally used in `this.map` was not. 

I’m not sure the best way to fix this. Now that I know the problem, the workaround is obvious, but it seems like something we should fix because it was quite difficult to figure out why my rules weren’t working.

This is the same problem first reported by @jpetitcolas [here](https://github.com/cssinjs/jss/issues/664#issuecomment-370729498), in whose case the error was caused by using `:after` instead of the more correct `::after`.

### PR DESCRIPTION
**Pull request by kof**
__What would you like to add/fix?__

Current linking logic causes too many bugs. This approach simplifies it. We are not linking any more using selector, we create rules using insertRule API always when we need to link a rule.

__Corresponding issue (if exists):__

- [x] Need to test which currently open issues it fixes.
- [x] Need to check how linking works with nesting and container rules like media queries.

Fixes #815, #710, #664

### CODE REVIEW

**Comment by kof** [comment]
This PR seems to be ready

**Comment by kof** [comment]
Ok added a test with media query, its not ready, fixing it.

File: packages/jss/src/StyleSheet.js [hunk 1]
```diff
@@ -34,7 +31,6 @@ export default class StyleSheet {
   constructor(styles: Object, options: StyleSheetOptions) {
     this.attached = false
     this.deployed = false
-    this.linked = false
```
Comment (HenriBeck) [inline packages/jss/src/StyleSheet.js]: Why did you remove the linked property?

Comment (kof) [reply packages/jss/src/StyleSheet.js]: because we don't need it any more, if options.link is true, then it is always linked, there is no separate sheet.link() call.

Comment (HenriBeck) [reply packages/jss/src/StyleSheet.js]: Yeah makes sense

**Comment by kof** [comment]
Should fix (still verifying) #815, #710, #664
@TrySound @HenriBeck please review the last commit

**Comment by TrySound** [comment]
Looks good to me

**Comment by kof** [comment]
Merged
